### ISSUE TITLE
Audio glitch issue with my Dell XPS 8940

### ISSUE THREAD

**Issue by inkpool** [daniyo27/XPS8940-OpenCore#1]
Basically, I have the same machine as yours. Mine is i5-10400, and I am using an AMD GPU. 

Everything went smooth with your EFI. And my modification to the GPU works well.

However, the audio has a very annoying issue: the sound glitches whatever audio device I am using (airplay, Bluetooth, 3.5mm plug). I think it was not the issue with audio driver.

I got two Dell XPS 8940, and the same glitches happen on both machines.

Do you have any idea what could happen to my configurations?

**Comment by daniyo27** [comment]
What do you see inside Hackintool under Audio devices? Here is mine.

<img width="1283" alt="Screen Shot 2021-04-11 at 11 46 04 PM" src="https://user-images.githubusercontent.com/11026113/114351927-1647e000-9b20-11eb-9a3a-3321b49b4157.png">

If it is the same, I would check your DRM settings 
https://dortania.github.io/OpenCore-Post-Install/universal/drm.html#testing-hardware-acceleration-and-decoding

**Comment by inkpool** [comment]
Thanks for the help.

The info under audio device is exactly the same as yours.  And the HW acceleration is fully supported.

I don't think it is an issue with the audio driver, since airplay and Bluetooth all have this issue, even an external USB audio DAC.

I am thinking about the CPU, because that is the only difference between us...

**Comment by daniyo27** [comment]
I highly doubt that the CPU is causing this. Is your BIOS fully up to date? I would try that first, if it doesn't work still, boot to **Windows** and generate all the patches in **SSDTime**. IRQ patch is the fix for audio.

If this fixes it please upload/share your files here for others to use.

**Comment by inkpool** [comment]
I think it is a CPU issue too. Actually, everything is glitching not only the sound.

I have checked the SSDT in the windows, it is the same as yours.

For the BIOS, it is 2.0.11 too. I don't know if there are any settings in the BIOS I could pay attention to.

**Comment by daniyo27** [comment]
Disable all security functions (Intel SGX) etc. I only followed what Dortania guide for BIOS settings. 

Maybe it would be a wise decision to start without GPU at all first and see if that is causing things wrong. I highly doubt i5 10400 is the issue because it is natively supported.

**Comment by inkpool** [comment]
I grabbed a G5 5090 and the same issue happened on it.

I have tried three Dell machines which all encountering this issue so far. (2 * XPS 8940 with 10400, G5 5090 with 10400f)

**Comment by daniyo27** [comment]
Could you please record a video of the glitching? You mention that it is not only sound?

**Comment by inkpool** [comment]
The root cause is my 5500XT GPU. After I removed it and use the UHD630, the glitches go away.

BTW, can you use Intel GPU to power two monitors?

**Comment by daniyo27** [comment]
Yes, the iGPU should work with both ports.

Try again with your 5500XT but add this boot-arg **agdpmod=pikera**
