### ISSUE TITLE
Dell XPS SE: 8940

### ISSUE THREAD

**Issue by deonthomasgy** [daniyo27/XPS8940-OpenCore#2]
hey, can you help me get my XPS 8940 working. The only difference between our setup is that I have a GTX 660 (GK106). Please let me know if you're interested in working with me to get this done.

**Comment by dandantsui** [comment]
You most likely have a GK 106 GTX 660 and is not compatible and will give graphical ram buffer artifacts.

[https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/nvidia-gpu.html#kepler-series-gtx-6xx-7xx]

**Comment by daniyo27** [comment]
You most likely have a GK 106 GTX 660 and is not compatible and will give graphical ram buffer artifacts.

https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/nvidia-gpu.html#kepler-series-gtx-6xx-7xx

**Comment by deonthomasgy** [comment]
Yeah I read that, I think I have a Quadro in a server k2000 that I can swap it with. I just need help getting the initial usb booted to install it. - Also I read that some user was able to use the GTX 660 and the memory leak is fixed. 
https://github.com/khronokernel/Catalina-GPU-Buyers-Guide/issues/4

**Comment by deonthomasgy** [comment]
ops, looks like you are right, GTX 660 is crap.

**Comment by daniyo27** [comment]
There is little to no incentive for the GTX 660 to be used. The issue you referenced only pertains to using Web Driver which is only compatible up to High Sierra.

I would cut your losses and just throw a RX 550 on or something!

Even these budget options should do well.
GT 740 (GK107 variant)
GT 730 (GK208 variant)
GT 720
GT 710 (GK208 variant)

**Comment by deonthomasgy** [comment]
I got this GTX 660 free, a friend has quite a few old GPUs i'll find out if he has a compatible one. I tend to prefer Nvidia. As it works well with Windows/Linux.

**Comment by deonthomasgy** [comment]
![20200505_123046](https://user-images.githubusercontent.com/150036/125725575-b525ca94-f618-4b68-9778-e71a7aeec9d8.jpg)
I got this!

**Comment by deonthomasgy** [comment]
if you can prepare the OpenCore USB and zip/rar upload somewhere that I can use, we can work something out on Paypal.

**Comment by daniyo27** [comment]
The K2000 should be plug-n-play with my config as I run a GTX 770 personally. Feel free to just download the .zip I've made already and fill your SN info and try.

**Comment by deonthomasgy** [comment]
ok great, I'll get the K2000 in the morning, if you're available at some time, I can setup a remote session to the PC for you to do it. Just imagine i'm absolute noob at mac mods and rather $ to get it sorted. I normally use Teamviewer or Anydesk to support client so either of this can work for this task. Let me know.

**Comment by deonthomasgy** [comment]
Hey @daniyo27 looks like the XPS will have to wait. I manage to install 11.4 on Dell Latitude e7390 and it's working perfectly. Only things that are missing is 3-4 finger gestures (not sure if trackpad supports) and headphone mic does not work. 

Thank you for your support. Keep up the good work.
