### ISSUE TITLE
Question about extended Graphic Card

### ISSUE THREAD

**Issue by lugokeT** [daniyo27/XPS8940-OpenCore#3]
Hello daniyo27,

Can't get internal graphic working because I have newer model with i7 11700 uhd750!

Yesterday I bought an Radeon HD 7750 but nothing is showing from output of Radeon Card.
Which Graphic Card should I use?
Maybee bios lock the graphic card ?
You use an Radeon,too. How did you get working.
And my Audio over ALC with your config does not work. Do you have an idea why?

Please help.

Regards

Lugoket

**Comment by daniyo27** [comment]
What makes you think that 11th gen Intel would have working graphics let alone proper CPU ID? No Apple Mac has come with 11th gen and thus won't be supported.

**Comment by lugokeT** [comment]
Hello daniyo27,

thanks for quick answer.

I only can get in system with fake CPU ID with onboard Vesa drivers for now. 
Audio is working with Layout ID 1 for now.

Would the extended Graphic Card GTX 770 2 GB work?
Because i have the feeling that Dell don't allow all Graphic Cards.
Did you bought your XPS 8940 with ready shipped GTX 770 2GB from Dell or do you insert the Graphic Card separately after buying?

Regards.

**Comment by superwangjia** [comment]
I have 11700  too，my GPU is gtx960

**Comment by daniyo27** [comment]
Do your own homework please. The dortania guides are there for a reason.

GTX960 has not been supported since High Sierra.

11th gen Intel CPU's are not supported and never will until Apple decides to release one. As you know Apple is releasing M1 chips and they will not likely release any more Intel CPU's
